#
#Wed May 06 14:01:17 CEST 2026
Simple_Item_Form_Size=450/550
auto_add_perfect_match=false
card_view_item_description=214\#
card_view_settings_dialog_size=500/400
default_insert_view=0
default_search_view=1
enabled=true
export_fields=
field_definitions={150/&/null/&/true/&/true/&/true/&/true/&/lblSummary}{1/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{152/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{3/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{151/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{2/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{28/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{154/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{29/&/null/&/true/&/false/&/false/&/false/&/lblSummary}{205/&/null/&/true/&/false/&/false/&/false/&/lblTechnicalInfo}{206/&/null/&/true/&/false/&/false/&/false/&/lblTechnicalInfo}{218/&/null/&/true/&/false/&/false/&/false/&/lblTechnicalInfo}{207/&/null/&/true/&/false/&/false/&/false/&/lblTechnicalInfo}{208/&/null/&/true/&/false/&/false/&/false/&/lblTechnicalInfo}{222/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{4/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{5/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{213/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{153/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{155/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{34/&/null/&/true/&/false/&/false/&/false/&/lblInformation}{202/&/null/&/true/&/false/&/false/&/false/&/null}{216/&/null/&/true/&/false/&/false/&/false/&/null}{204/&/null/&/true/&/false/&/false/&/false/&/null}{215/&/null/&/true/&/false/&/false/&/false/&/null}{203/&/null/&/true/&/false/&/false/&/false/&/null}{221/&/null/&/true/&/false/&/false/&/false/&/null}{220/&/null/&/true/&/false/&/false/&/false/&/null}{219/&/null/&/true/&/false/&/false/&/false/&/null}{201/&/null/&/false/&/false/&/false/&/false/&/null}{217/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{214/&/null/&/false/&/false/&/false/&/false/&/null}{231/&/null/&/true/&/false/&/false/&/false/&/null}{232/&/null/&/true/&/false/&/false/&/false/&/null}{233/&/null/&/true/&/false/&/false/&/false/&/null}{234/&/null/&/true/&/false/&/false/&/false/&/null}{235/&/null/&/true/&/false/&/false/&/false/&/null}{236/&/null/&/true/&/false/&/false/&/false/&/null}{237/&/null/&/true/&/false/&/false/&/false/&/null}{238/&/null/&/true/&/false/&/false/&/false/&/null}{239/&/null/&/true/&/false/&/false/&/false/&/null}{240/&/null/&/true/&/false/&/false/&/false/&/null}{101/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{104/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{105/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{102/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{103/&/null/&/false/&/false/&/false/&/false/&/lblSummary}{0/&/ID/&/false/&/false/&/false/&/false/&/null}
field_settings_dialog_size=1078/630
file_import_dialog_size=550/600
file_import_directory_usage=0
file_import_online_service=
file_import_online_service_mode=
file_import_online_service_region=
file_import_recursive=false
file_import_use_online_service=true
filter_dialog_size=700/400
group_by=
import_cd_container=
import_cd_dialog_size=600/900
import_cd_storagemedium=
import_local_art=true
import_local_art_keywords=front,cover,case
import_local_art_recurses=true
item_form_size=700/600
loan_form_size=500/500
mass_update_always_use_first=false
mass_update_mode=
mass_update_region=
mass_update_server=
mass_update_use_original_service_settings=false
online_search_default_mode=
online_search_default_region=en
online_search_default_server=The Movie Database (TV Series)
online_search_field_overwrite_settings=
online_search_field_settings_dialog_size=600/450
online_search_form_size=1129/886
online_search_overwrite=false
online_search_retrieved_fields=1\#2\#3\#4\#5\#28\#29\#34\#0\#205\#206\#101\#102\#103\#104\#105\#217\#218\#222\#213\#207\#208\#214\#231\#232\#233\#234\#235\#236\#237\#238\#239\#240\#201\#150\#151\#152\#153\#154\#155\#
quick_filter_default_field=0
quick_view_field_definitions={1/&/true/&/Horizontal/&/0}{151/&/true/&/Horizontal/&/0}{152/&/true/&/Horizontal/&/0}{3/&/true/&/Horizontal/&/0}{150/&/false/&/Horizontal/&/0}{201/&/false/&/Horizontal/&/0}{217/&/false/&/Horizontal/&/0}{214/&/false/&/Horizontal/&/0}{101/&/false/&/Horizontal/&/0}{104/&/false/&/Horizontal/&/0}{105/&/false/&/Horizontal/&/0}{102/&/false/&/Horizontal/&/0}{103/&/false/&/Horizontal/&/0}{202/&/false/&/Horizontal/&/0}{216/&/false/&/Horizontal/&/0}{204/&/false/&/Horizontal/&/0}{215/&/false/&/Horizontal/&/0}{203/&/false/&/Horizontal/&/0}{221/&/false/&/Horizontal/&/0}{220/&/false/&/Horizontal/&/0}{219/&/false/&/Horizontal/&/0}{5/&/true/&/Horizontal/&/0}{4/&/true/&/Horizontal/&/0}{155/&/true/&/Horizontal/&/0}{213/&/true/&/Horizontal/&/0}{205/&/false/&/Horizontal/&/0}{34/&/true/&/Horizontal/&/0}{218/&/false/&/Horizontal/&/0}{153/&/true/&/Horizontal/&/0}{206/&/false/&/Horizontal/&/0}{231/&/false/&/Horizontal/&/0}{232/&/false/&/Horizontal/&/0}{233/&/false/&/Horizontal/&/0}{234/&/false/&/Horizontal/&/0}{235/&/false/&/Horizontal/&/0}{236/&/false/&/Horizontal/&/0}{237/&/false/&/Horizontal/&/0}{238/&/false/&/Horizontal/&/0}{239/&/false/&/Horizontal/&/0}{240/&/false/&/Horizontal/&/0}{154/&/true/&/Horizontal/&/0}{207/&/false/&/Horizontal/&/0}{208/&/false/&/Horizontal/&/0}{28/&/true/&/Horizontal/&/0}{29/&/true/&/Horizontal/&/0}{222/&/true/&/Horizontal/&/0}{2/&/true/&/Horizontal/&/0}
quick_view_settings_dialog_size=500/534
report_file=
report_type=
search_order_field_indices=
selected_report=
simple_item_view_size=450/550
synchronizer_dialog_size=550/600
table_column_order=150\#152\#154\#
table_settings=[72]
table_view_settings_dialog_size=500/400
title_cleanup=axxo,dvdrip,cdrip,dvd-rip,cd-rip
title_cleanup_regex=
web_overview_field_definitions={202/&/true}{216/&/true}{204/&/true}{215/&/true}{203/&/true}{221/&/true}{220/&/true}{219/&/true}{4/&/true}{213/&/true}{155/&/true}{205/&/true}{151/&/true}{5/&/true}{34/&/true}{218/&/true}{3/&/true}{0/&/false}{201/&/true}{217/&/true}{214/&/true}{153/&/true}{206/&/true}{154/&/true}{207/&/true}{208/&/true}{28/&/true}{29/&/true}{222/&/true}{150/&/true}{1/&/true}{101/&/true}{104/&/true}{105/&/true}{102/&/true}{103/&/true}{2/&/true}{152/&/true}
web_view_field_definitions={150}{1}{151}{3}{5}{4}{28}{202}{216}{204}{215}{203}{221}{220}{219}{213}{155}{205}{34}{218}{153}{206}{154}{207}{208}{29}{222}{2}{152}
